version: "3"
services:
    node-server:
        container_name: node-server
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - $NETWORK_NAME
        environment:
            - DB_HOST=$MONGODB_SERVER
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
        restart: unless-stopped
        ports:
            - $NODE_HOST_PORT:$NODE_DOCKER_PORT
        links:
            - $MONGODB_SERVER
        depends_on:
            - $MONGODB_SERVER
    mongodb:
        container_name: mongodb
        image: mongo:4.2.23
        networks:
            - $NETWORK_NAME
        restart: unless-stopped
        ports:
            - $MONGODB_HOST_PORT:$MONGODB_DOCKER_PORT
        environment:
            - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        volumes:
            - ./mongodb-database/:/docker-entrypoint-initdb.d/
    mongo-express:
        container_name: mongo-express
        image: mongo-express:0.54.0
        networks:
            - $NETWORK_NAME
        restart: unless-stopped
        ports:
            - $MONGO_EXPRESS_HOST_PORT:$MONGO_EXPRESS_DOCKER_PORT
        environment:
            - ME_CONFIG_MONGODB_SERVER=$MONGODB_SERVER
            - ME_CONFIG_MONGODB_PORT=$MONGODB_DOCKER_PORT
            - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
            - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
        depends_on:
            - $MONGODB_SERVER

networks:
    node_mongo_mongoexpress_network:
        name: $NETWORK_NAME
        driver: bridge